### ISSUE TITLE
more words

### ISSUE THREAD

**Issue by lukeapage** [marcoagpinto/aoo-mozilla-en-dict#19]
Am spell-checking a lot of blog posts with this dictionary - thanks! found a few more for consideration..

combatted - https://en.wiktionary.org/wiki/combatted (or alternative combated)
shorthands (shorthand is added, but "Use these shorthands for shorter code")
programatically - https://en.wiktionary.org/wiki/programatically
crosshairs - (cross-hair is added) https://en.wiktionary.org/wiki/crosshair
debounc(e|es|ing|ed) - https://en.wiktionary.org/wiki/debounce
yuck - you have yucky
gyro - https://en.wiktionary.org/wiki/gyro
repo - https://en.wiktionary.org/wiki/repo (in my case source code repository)
performant - https://en.wiktionary.org/wiki/performant
plugin - you have plug-in
unopinionated - https://en.wiktionary.org/wiki/unopinionated
useable - alt. spelling - https://en.wiktionary.org/wiki/useable
anymore - https://en.wiktionary.org/wiki/anymore
unicity - https://en.wiktionary.org/wiki/unicity
artifact(s) - https://en.wiktionary.org/wiki/artifacts
thusly - https://en.wiktionary.org/wiki/thusly
spandex - https://en.wiktionary.org/wiki/spandex

**Comment by marcoagpinto** [comment]
Hello Luke,

I have added the following words:
8913) combatting + combatted (another way of combating and combated)
8914) cross-hair (removed, Oxford says it is two words)
8915) debounce (+s +ing +ed - Wiktionary)
8916) yuck + yuk (Oxford: informal)
8917) gyro (+plural)
8918) repo (+plural - source code repository - Wiktionary)
8919) unopinionated
8920) useable (another way of usable)
8921) unicity
8922) thusly (Oxford: informal)
8923) spandex

Please notice that I always check first in the Oxford Dictionaries since they are the premier source for British, then on Collins and later on the other sources.

Here are my comments:
1. combatted + combatting
Oxford: "verb (combats, combating or combatting, combated or combatted)"

2. shorthands
shorthand (Oxford says it is a mass noun and in the dozens of examples there isn't a single plural)

3. programatically
programmatically has two "m" and I added it this month already.

4. crosshairs
http://www.oxforddictionaries.com/definition/english/cross-hairs?q=crosshairs
it is two words, so I have removed it from en_GB

5. performant
Added it this month already

6. plugin
http://www.oxforddictionaries.com/definition/english/plug-in?q=plugin
it is "plug-in" in GB

7. anymore
http://www.oxforddictionaries.com/definition/english/anymore
it is American, in GB it is two words: "any more"

8. artifact(s)
http://www.oxforddictionaries.com/definition/english/artefact?q=artifacts
It is American. In GB is artefact

Thanks for the words!

Kind regards,
     >Marco A.G.Pinto
       ---------------------
