### ISSUE TITLE
Where is the update to dic and aff file?

### ISSUE THREAD

**Issue by Ding-adong** [marcoagpinto/aoo-mozilla-en-dict#39]
Over a month ago I'd sent you a new massively **improved** aff and dic files, fixing over 10,000 errors and you have not done anything. I have a group of pissed off people wondering what the hell are you doing. Do you think its funny wasting our time? Is it too difficult for you to comprehend basic tasks.

Why the fuck are you adding commits to your **inferior** dic file?

1:- Download this https://github.com/Ding-adong/aoo-mozilla-en-dict/blob/master/Dicaff.rar
2:- Add your commits since middle of March to my updated aff and dic files then release it, so we British people can have a better dictionary and less time spent on spellchecking.

Is this too difficult for you?

**Comment by marcoagpinto** [comment]
Yes, it is very difficult for me.

I don't add words just because someone says it is good or bad, I add words after I verify them ONE BY ONE in the dictionaries I mention in the .aff:
#   1) Oxford Dictionaries;    5) Merriam-Webster Dictionary (used with caution ⚠);
#   2) Collins Dictionary;     6) Wiktionary (used with caution ⚠);
#   3) Macmillan Dictionary;   7) Wikipedia (used with caution ⚠);
#   4) Cambridge Dictionary;   8) Physical dictionaries.

**Comment by Ding-adong** [comment]
This is ridiculous. We are all British and we do know our own language.  All you have to do is check my dic file then release it. Adding one by one would take you forever. You can not do all this on your own and you know it. The dic will never get finished. Stop fucking around and use your common sense.

**Comment by marcoagpinto** [comment]
Anyway, for a month or so that I have been focused in removing duplicates, merge words using flags, adding possessives and plurals.

I have also been slowly improving the flags in the .aff .

I am also focusing in adding words from important articles on Wikipedia so that one can write essays about the subject with most of the words in the .dic .

This is my task currently.
