### ISSUE TITLE
Add permaculture

### ISSUE THREAD

**Issue by usertogo** [marcoagpinto/aoo-mozilla-en-dict#41]
How can it be - I use Linux and open source libreoffice but everywhere I find the word 'permaculture' is still not known and accepted in the spell checker libraries? the word is already 42 years old ...
even if in the past there had been illusions about copyright or trademark that should not prevent a word that receives so much use to be included...
Thanks!

**Comment by marcoagpinto** [comment]
Hello!

That word has been in the speller since 2014:
11-DEC-2014
4701) permalink (+plural)
**4702) permaculture**

But I have just added the plural +possessive, along with other related words:
4-MAR-2020
**55232) permaculture (added plural +'s)**
55233) permacultural
55234) permaculturist (+plural +'s)
55235) permaculturalist (+plural +'s)


It will be available in the monthly update.

Thanks!

**Comment by marcoagpinto** [comment]
Ahhhh... I only add words to the British speller.

If you mean other variants, you will need to contact Kevin Atkinson (and good luck with that).
